import type {
  AssetId,
  CategoryCanonicalPath,
  CategoryId,
  LocalizedText,
  NonEmptyReadonlyArray,
  SeoSlugPath,
  SlugSegment,
} from './primitives'

export type CategoryDepth = 0 | 1 | 2 | 3 | 4

export type CategoryKind =
  | 'catalog-root'
  | 'measurement-family'
  | 'measurement-principle'
  | 'product-function'
  | 'series-group'
  | 'accessory-group'

export type CategoryFacetKey =
  | 'measurementRange'
  | 'outputSignal'
  | 'processConnection'
  | 'electricalConnection'
  | 'accuracyClass'
  | 'ingressProtection'
  | 'mediaCompatibility'
  | 'certification'
  | 'industry'
  | 'availability'

export interface CategorySeoInput {
  readonly titlePattern: string
  readonly descriptionPattern: string
  readonly indexable: boolean
  readonly canonicalPath: CategoryCanonicalPath
}

export interface CategoryNode {
  readonly id: CategoryId
  readonly parentId: CategoryId | null
  readonly depth: CategoryDepth
  readonly kind: CategoryKind
  readonly slug: SlugSegment
  readonly slugPath: SeoSlugPath
  readonly canonicalPath: CategoryCanonicalPath
  readonly name: LocalizedText
  readonly description: LocalizedText
  readonly iconAssetId?: AssetId
  readonly sortOrder: number
  readonly facetKeys: readonly CategoryFacetKey[]
  readonly seo: CategorySeoInput
  readonly children?: readonly CategoryNode[]
}

export interface CategoryTree {
  readonly version: 'category-tree-v1'
  readonly root: CategoryNode
  readonly indexKeys: readonly CategoryFacetKey[]
  readonly maxDepth: CategoryDepth
}

const rootCategoryId = 'cat_industrial_sensors'

const seo = (
  canonicalPath: CategoryCanonicalPath,
  descriptionPattern = 'Browse {category} by basic parameters, signal output, and engineering application.',
): CategorySeoInput => ({
  indexable: true,
  canonicalPath,
  titlePattern: '{category} | {brand} Product Center',
  descriptionPattern,
})

export const industrialSensorCategoryTree = {
  version: 'category-tree-v1',
  maxDepth: 4,
  indexKeys: [
    'measurementRange',
    'outputSignal',
    'processConnection',
    'electricalConnection',
    'accuracyClass',
    'ingressProtection',
    'mediaCompatibility',
    'certification',
    'industry',
    'availability',
  ],
  root: {
    id: rootCategoryId,
    parentId: null,
    depth: 0,
    kind: 'catalog-root',
    slug: 'industrial-sensors',
    slugPath: 'industrial-sensors',
    canonicalPath: '/products/industrial-sensors',
    name: { en: 'Product Center', zh: '产品中心' },
    description: {
      en: 'A product center organized by valves, pressure, temperature, level, gauges, switches, and wireless transmitters.',
      zh: '按阀、压力、温度、液位、压力表、压力开关和无线变送器组织的产品中心。',
    },
    sortOrder: 0,
    facetKeys: ['industry', 'availability', 'certification'],
    seo: seo('/products/industrial-sensors', 'Browse Yufavor product families by category, basic parameters, and application needs.'),
    children: [
      {
        id: 'cat_industrial_valves',
        parentId: rootCategoryId,
        depth: 1,
        kind: 'measurement-family',
        slug: 'valves',
        slugPath: 'valves',
        canonicalPath: '/products/valves',
        name: { en: 'Valves', zh: '阀' },
        description: { en: 'Solenoid, proportional, regulating, safety, and manifold valve products.', zh: '电磁阀、比例阀、调压阀、安全阀和阀组产品。' },
        sortOrder: 10,
        facetKeys: ['processConnection', 'mediaCompatibility', 'certification', 'availability'],
        seo: seo('/products/valves', 'Select {category} by connection, medium, pressure class, and function.'),
        children: [
          {
            id: 'cat_solenoid_valves',
            parentId: 'cat_industrial_valves',
            depth: 2,
            kind: 'product-function',
            slug: 'solenoid-valves',
            slugPath: 'valves/solenoid-valves',
            canonicalPath: '/products/valves/solenoid-valves',
            name: { en: 'Solenoid Valves', zh: '电磁阀' },
            description: { en: 'Electromagnetic on-off valves for industrial control loops.', zh: '用于工业控制回路的电磁开关阀。' },
            sortOrder: 10,
            facetKeys: ['processConnection', 'mediaCompatibility', 'availability'],
            seo: seo('/products/valves/solenoid-valves'),
          },
          {
            id: 'cat_proportional_valves',
            parentId: 'cat_industrial_valves',
            depth: 2,
            kind: 'product-function',
            slug: 'proportional-valves',
            slugPath: 'valves/proportional-valves',
            canonicalPath: '/products/valves/proportional-valves',
            name: { en: 'Proportional Valves', zh: '比例阀' },
            description: { en: 'Proportional valve products for continuous flow and pressure control.', zh: '用于连续流量与压力控制的比例阀产品。' },
            sortOrder: 20,
            facetKeys: ['processConnection', 'mediaCompatibility', 'outputSignal'],
            seo: seo('/products/valves/proportional-valves'),
          },
          {
            id: 'cat_pressure_regulating_valves',
            parentId: 'cat_industrial_valves',
            depth: 2,
            kind: 'product-function',
            slug: 'pressure-regulating-valves',
            slugPath: 'valves/pressure-regulating-valves',
            canonicalPath: '/products/valves/pressure-regulating-valves',
            name: { en: 'Pressure Regulating Valves', zh: '调压阀' },
            description: { en: 'Pressure regulating valves for stable downstream pressure control.', zh: '用于稳定下游压力控制的调压阀。' },
            sortOrder: 30,
            facetKeys: ['measurementRange', 'processConnection', 'mediaCompatibility'],
            seo: seo('/products/valves/pressure-regulating-valves'),
          },
          {
            id: 'cat_safety_valves',
            parentId: 'cat_industrial_valves',
            depth: 2,
            kind: 'product-function',
            slug: 'safety-valves',
            slugPath: 'valves/safety-valves',
            canonicalPath: '/products/valves/safety-valves',
            name: { en: 'Safety Valves', zh: '安全阀' },
            description: { en: 'Safety valves for pressure relief and equipment protection.', zh: '用于泄压与设备保护的安全阀。' },
            sortOrder: 40,
            facetKeys: ['measurementRange', 'processConnection', 'certification'],
            seo: seo('/products/valves/safety-valves'),
          },
          {
            id: 'cat_valve_manifolds_protection',
            parentId: 'cat_industrial_valves',
            depth: 2,
            kind: 'accessory-group',
            slug: 'manifold-and-protection',
            slugPath: 'valves/manifold-and-protection',
            canonicalPath: '/products/valves/manifold-and-protection',
            name: { en: 'Manifolds and Protection', zh: '阀组与安全保护装置' },
            description: { en: 'Manifold and protection devices for instrument installation.', zh: '用于仪表安装配套的阀组与保护装置。' },
            sortOrder: 50,
            facetKeys: ['processConnection', 'certification', 'availability'],
            seo: seo('/products/valves/manifold-and-protection'),
          },
        ],
      },
      {
        id: 'cat_pressure_sensors',
        parentId: rootCategoryId,
        depth: 1,
        kind: 'measurement-family',
        slug: 'pressure-sensors',
        slugPath: 'pressure-sensors',
        canonicalPath: '/products/pressure-sensors',
        name: { en: 'Pressure Sensors', zh: '压力传感器' },
        description: { en: 'Transmitters and sensors for gauge, differential, high, low, and explosion-proof pressure measurement.', zh: '覆盖压力变送器、差压、高压、微压和防爆压力测量产品。' },
        sortOrder: 20,
        facetKeys: ['measurementRange', 'outputSignal', 'processConnection', 'accuracyClass', 'ingressProtection'],
        seo: seo('/products/pressure-sensors', 'Compare {category} by range, signal output, connection, accuracy, and protection.'),
        children: [
          {
            id: 'cat_pressure_transmitters',
            parentId: 'cat_pressure_sensors',
            depth: 2,
            kind: 'product-function',
            slug: 'pressure-transmitters',
            slugPath: 'pressure-sensors/pressure-transmitters',
            canonicalPath: '/products/pressure-sensors/pressure-transmitters',
            name: { en: 'Pressure Transmitters', zh: '压力变送器' },
            description: { en: 'Continuous pressure measurement with analog, voltage, or digital output.', zh: '支持电流、电压或数字输出的连续压力测量产品。' },
            sortOrder: 10,
            facetKeys: ['measurementRange', 'outputSignal', 'processConnection', 'electricalConnection', 'accuracyClass'],
            seo: seo('/products/pressure-sensors/pressure-transmitters'),
          },
          {
            id: 'cat_differential_pressure',
            parentId: 'cat_pressure_sensors',
            depth: 2,
            kind: 'measurement-principle',
            slug: 'differential-pressure-sensors',
            slugPath: 'pressure-sensors/differential-pressure-sensors',
            canonicalPath: '/products/pressure-sensors/differential-pressure-sensors',
            name: { en: 'Differential Pressure Sensors', zh: '差压传感器' },
            description: { en: 'Differential pressure sensors for filters, HVAC, flow elements, and clean rooms.', zh: '用于过滤、暖通、流量元件和洁净室的差压传感器。' },
            sortOrder: 20,
            facetKeys: ['measurementRange', 'outputSignal', 'accuracyClass', 'ingressProtection'],
            seo: seo('/products/pressure-sensors/differential-pressure-sensors'),
          },
          {
            id: 'cat_high_pressure_sensors',
            parentId: 'cat_pressure_sensors',
            depth: 2,
            kind: 'measurement-principle',
            slug: 'high-pressure-sensors',
            slugPath: 'pressure-sensors/high-pressure-sensors',
            canonicalPath: '/products/pressure-sensors/high-pressure-sensors',
            name: { en: 'High Pressure Sensors', zh: '高压传感器' },
            description: { en: 'Pressure sensors for hydraulic, testing, and high-pressure systems.', zh: '用于液压、测试和高压系统的压力传感器。' },
            sortOrder: 30,
            facetKeys: ['measurementRange', 'outputSignal', 'processConnection', 'accuracyClass'],
            seo: seo('/products/pressure-sensors/high-pressure-sensors'),
          },
          {
            id: 'cat_low_pressure_sensors',
            parentId: 'cat_pressure_sensors',
            depth: 2,
            kind: 'measurement-principle',
            slug: 'low-pressure-sensors',
            slugPath: 'pressure-sensors/low-pressure-sensors',
            canonicalPath: '/products/pressure-sensors/low-pressure-sensors',
            name: { en: 'Low Pressure Sensors', zh: '微压传感器' },
            description: { en: 'Low pressure sensors for air, HVAC, and light-duty pressure monitoring.', zh: '用于空气、暖通和轻载压力监测的微压传感器。' },
            sortOrder: 40,
            facetKeys: ['measurementRange', 'outputSignal', 'accuracyClass'],
            seo: seo('/products/pressure-sensors/low-pressure-sensors'),
          },
          {
            id: 'cat_explosion_proof_pressure_sensors',
            parentId: 'cat_pressure_sensors',
            depth: 2,
            kind: 'product-function',
            slug: 'explosion-proof-pressure-sensors',
            slugPath: 'pressure-sensors/explosion-proof-pressure-sensors',
            canonicalPath: '/products/pressure-sensors/explosion-proof-pressure-sensors',
            name: { en: 'Explosion-proof Pressure Sensors', zh: '防爆压力传感器' },
            description: { en: 'Pressure sensors prepared for hazardous-area and explosion-proof applications.', zh: '面向危险区域与防爆应用的压力传感器。' },
            sortOrder: 50,
            facetKeys: ['measurementRange', 'outputSignal', 'certification', 'ingressProtection'],
            seo: seo('/products/pressure-sensors/explosion-proof-pressure-sensors'),
          },
        ],
      },
      {
        id: 'cat_temperature_sensors',
        parentId: rootCategoryId,
        depth: 1,
        kind: 'measurement-family',
        slug: 'temperature-sensors',
        slugPath: 'temperature-sensors',
        canonicalPath: '/products/temperature-sensors',
        name: { en: 'Temperature Sensors', zh: '温度传感器' },
        description: { en: 'Temperature transmitters, RTDs, thermocouples, integrated sensors, and explosion-proof models.', zh: '覆盖温度变送器、热电阻、热电偶、一体化和防爆温度传感器。' },
        sortOrder: 30,
        facetKeys: ['measurementRange', 'outputSignal', 'processConnection', 'accuracyClass', 'certification'],
        seo: seo('/products/temperature-sensors', 'Select {category} by temperature range, signal output, connection, and accuracy.'),
        children: [
          {
            id: 'cat_temperature_transmitters',
            parentId: 'cat_temperature_sensors',
            depth: 2,
            kind: 'product-function',
            slug: 'temperature-transmitters',
            slugPath: 'temperature-sensors/temperature-transmitters',
            canonicalPath: '/products/temperature-sensors/temperature-transmitters',
            name: { en: 'Temperature Transmitters', zh: '温度变送器' },
            description: { en: 'Signal conditioners and transmitters for RTD and thermocouple inputs.', zh: '用于 RTD 和热电偶输入的信号调理器与变送器。' },
            sortOrder: 10,
            facetKeys: ['outputSignal', 'accuracyClass', 'certification'],
            seo: seo('/products/temperature-sensors/temperature-transmitters'),
          },
          {
            id: 'cat_rtd_sensors',
            parentId: 'cat_temperature_sensors',
            depth: 2,
            kind: 'measurement-principle',
            slug: 'rtd',
            slugPath: 'temperature-sensors/rtd',
            canonicalPath: '/products/temperature-sensors/rtd',
            name: { en: 'RTD Sensors', zh: '热电阻 RTD' },
            description: { en: 'RTD temperature sensors for industrial process measurement.', zh: '用于工业过程测温的热电阻传感器。' },
            sortOrder: 20,
            facetKeys: ['measurementRange', 'processConnection', 'accuracyClass'],
            seo: seo('/products/temperature-sensors/rtd'),
          },
          {
            id: 'cat_thermocouples',
            parentId: 'cat_temperature_sensors',
            depth: 2,
            kind: 'measurement-principle',
            slug: 'thermocouples',
            slugPath: 'temperature-sensors/thermocouples',
            canonicalPath: '/products/temperature-sensors/thermocouples',
            name: { en: 'Thermocouples', zh: '热电偶' },
            description: { en: 'Thermocouple probes and assemblies for wide temperature ranges.', zh: '用于宽温度范围的热电偶探头与组件。' },
            sortOrder: 30,
            facetKeys: ['measurementRange', 'processConnection', 'certification'],
            seo: seo('/products/temperature-sensors/thermocouples'),
          },
          {
            id: 'cat_temperature_measurement',
            parentId: 'cat_temperature_sensors',
            depth: 2,
            kind: 'product-function',
            slug: 'integrated-temperature-sensors',
            slugPath: 'temperature-sensors/integrated-temperature-sensors',
            canonicalPath: '/products/temperature-sensors/integrated-temperature-sensors',
            name: { en: 'Integrated Temperature Sensors', zh: '一体化温度传感器' },
            description: { en: 'Integrated temperature sensors with probe, housing, and signal output.', zh: '集成探杆、外壳和信号输出的一体化温度传感器。' },
            sortOrder: 40,
            facetKeys: ['measurementRange', 'outputSignal', 'processConnection'],
            seo: seo('/products/temperature-sensors/integrated-temperature-sensors'),
          },
          {
            id: 'cat_explosion_proof_temperature_sensors',
            parentId: 'cat_temperature_sensors',
            depth: 2,
            kind: 'product-function',
            slug: 'explosion-proof-temperature-sensors',
            slugPath: 'temperature-sensors/explosion-proof-temperature-sensors',
            canonicalPath: '/products/temperature-sensors/explosion-proof-temperature-sensors',
            name: { en: 'Explosion-proof Temperature Sensors', zh: '防爆温度传感器' },
            description: { en: 'Temperature sensors prepared for hazardous-area and explosion-proof applications.', zh: '面向危险区域与防爆应用的温度传感器。' },
            sortOrder: 50,
            facetKeys: ['measurementRange', 'outputSignal', 'certification'],
            seo: seo('/products/temperature-sensors/explosion-proof-temperature-sensors'),
          },
        ],
      },
      {
        id: 'cat_pressure_switches',
        parentId: rootCategoryId,
        depth: 1,
        kind: 'measurement-family',
        slug: 'pressure-switches',
        slugPath: 'pressure-switches',
        canonicalPath: '/products/pressure-switches',
        name: { en: 'Pressure Switches', zh: '压力开关' },
        description: { en: 'Mechanical, electronic, differential, and adjustable pressure switches.', zh: '机械式、电子式、差压和可调压力开关。' },
        sortOrder: 40,
        facetKeys: ['measurementRange', 'outputSignal', 'processConnection', 'electricalConnection', 'ingressProtection'],
        seo: seo('/products/pressure-switches', 'Select {category} by setpoint, pressure range, signal, and connection.'),
        children: [
          {
            id: 'cat_industrial_switches',
            parentId: 'cat_pressure_switches',
            depth: 2,
            kind: 'product-function',
            slug: 'mechanical-pressure-switches',
            slugPath: 'pressure-switches/mechanical-pressure-switches',
            canonicalPath: '/products/pressure-switches/mechanical-pressure-switches',
            name: { en: 'Mechanical Pressure Switches', zh: '机械压力开关' },
            description: { en: 'Mechanical pressure switches for equipment protection and control.', zh: '用于设备保护与控制的机械压力开关。' },
            sortOrder: 10,
            facetKeys: ['measurementRange', 'processConnection', 'electricalConnection'],
            seo: seo('/products/pressure-switches/mechanical-pressure-switches'),
          },
          {
            id: 'cat_electronic_pressure_switches',
            parentId: 'cat_pressure_switches',
            depth: 2,
            kind: 'product-function',
            slug: 'electronic-pressure-switches',
            slugPath: 'pressure-switches/electronic-pressure-switches',
            canonicalPath: '/products/pressure-switches/electronic-pressure-switches',
            name: { en: 'Electronic Pressure Switches', zh: '电子压力开关' },
            description: { en: 'Electronic pressure switches with display, output, and parameter settings.', zh: '带显示、输出和参数设置的电子压力开关。' },
            sortOrder: 20,
            facetKeys: ['measurementRange', 'outputSignal', 'electricalConnection'],
            seo: seo('/products/pressure-switches/electronic-pressure-switches'),
          },
          {
            id: 'cat_differential_pressure_switches',
            parentId: 'cat_pressure_switches',
            depth: 2,
            kind: 'product-function',
            slug: 'differential-pressure-switches',
            slugPath: 'pressure-switches/differential-pressure-switches',
            canonicalPath: '/products/pressure-switches/differential-pressure-switches',
            name: { en: 'Differential Pressure Switches', zh: '差压开关' },
            description: { en: 'Differential pressure switches for filters, fans, and flow monitoring.', zh: '用于过滤器、风机和流量监测的差压开关。' },
            sortOrder: 30,
            facetKeys: ['measurementRange', 'processConnection', 'accuracyClass'],
            seo: seo('/products/pressure-switches/differential-pressure-switches'),
          },
          {
            id: 'cat_adjustable_pressure_switches',
            parentId: 'cat_pressure_switches',
            depth: 2,
            kind: 'product-function',
            slug: 'adjustable-pressure-switches',
            slugPath: 'pressure-switches/adjustable-pressure-switches',
            canonicalPath: '/products/pressure-switches/adjustable-pressure-switches',
            name: { en: 'Adjustable Pressure Switches', zh: '可调压力开关' },
            description: { en: 'Adjustable pressure switches for configurable control points.', zh: '用于可配置控制点的可调压力开关。' },
            sortOrder: 40,
            facetKeys: ['measurementRange', 'processConnection', 'electricalConnection'],
            seo: seo('/products/pressure-switches/adjustable-pressure-switches'),
          },
        ],
      },
      {
        id: 'cat_level_sensors',
        parentId: rootCategoryId,
        depth: 1,
        kind: 'measurement-family',
        slug: 'level-sensors',
        slugPath: 'level-sensors',
        canonicalPath: '/products/level-sensors',
        name: { en: 'Level Sensors', zh: '液位传感器' },
        description: { en: 'Level sensors for tanks, wells, reservoirs, and process vessels.', zh: '用于水箱、水井、水库和过程容器的液位传感器。' },
        sortOrder: 50,
        facetKeys: ['measurementRange', 'outputSignal', 'mediaCompatibility', 'ingressProtection', 'certification'],
        seo: seo('/products/level-sensors', 'Select {category} by level range, medium, output signal, and protection.'),
        children: [
          {
            id: 'cat_submersible_level',
            parentId: 'cat_level_sensors',
            depth: 2,
            kind: 'measurement-principle',
            slug: 'submersible-level-sensors',
            slugPath: 'level-sensors/submersible-level-sensors',
            canonicalPath: '/products/level-sensors/submersible-level-sensors',
            name: { en: 'Submersible Level Sensors', zh: '投入式液位传感器' },
            description: { en: 'Hydrostatic level probes for water treatment, groundwater, tanks, and reservoirs.', zh: '用于水处理、地下水、水箱和水库的静压式液位探头。' },
            sortOrder: 10,
            facetKeys: ['measurementRange', 'outputSignal', 'mediaCompatibility', 'ingressProtection'],
            seo: seo('/products/level-sensors/submersible-level-sensors'),
          },
        ],
      },
      {
        id: 'cat_pressure_gauges',
        parentId: rootCategoryId,
        depth: 1,
        kind: 'measurement-family',
        slug: 'pressure-gauges',
        slugPath: 'pressure-gauges',
        canonicalPath: '/products/pressure-gauges',
        name: { en: 'Pressure Gauges', zh: '压力表' },
        description: { en: 'Mechanical, digital, and differential pressure gauges.', zh: '机械压力表、数字压力表和差压表。' },
        sortOrder: 60,
        facetKeys: ['measurementRange', 'accuracyClass', 'processConnection', 'certification'],
        seo: seo('/products/pressure-gauges', 'Select {category} by pressure range, display type, connection, and accuracy.'),
        children: [
          {
            id: 'cat_mechanical_pressure_gauges',
            parentId: 'cat_pressure_gauges',
            depth: 2,
            kind: 'product-function',
            slug: 'mechanical-pressure-gauges',
            slugPath: 'pressure-gauges/mechanical-pressure-gauges',
            canonicalPath: '/products/pressure-gauges/mechanical-pressure-gauges',
            name: { en: 'Mechanical Pressure Gauges', zh: '机械压力表' },
            description: { en: 'Mechanical dial pressure gauges for local indication.', zh: '用于现场指示的机械式压力表。' },
            sortOrder: 10,
            facetKeys: ['measurementRange', 'accuracyClass', 'processConnection'],
            seo: seo('/products/pressure-gauges/mechanical-pressure-gauges'),
          },
          {
            id: 'cat_digital_pressure_gauges',
            parentId: 'cat_pressure_gauges',
            depth: 2,
            kind: 'product-function',
            slug: 'digital-pressure-gauges',
            slugPath: 'pressure-gauges/digital-pressure-gauges',
            canonicalPath: '/products/pressure-gauges/digital-pressure-gauges',
            name: { en: 'Digital Pressure Gauges', zh: '数字压力表' },
            description: { en: 'Digital pressure gauges for high readability and parameter display.', zh: '用于高可读性与参数显示的数字压力表。' },
            sortOrder: 20,
            facetKeys: ['measurementRange', 'accuracyClass', 'outputSignal'],
            seo: seo('/products/pressure-gauges/digital-pressure-gauges'),
          },
          {
            id: 'cat_differential_pressure_gauges',
            parentId: 'cat_pressure_gauges',
            depth: 2,
            kind: 'measurement-principle',
            slug: 'differential-pressure-gauges',
            slugPath: 'pressure-gauges/differential-pressure-gauges',
            canonicalPath: '/products/pressure-gauges/differential-pressure-gauges',
            name: { en: 'Differential Pressure Gauges', zh: '差压表' },
            description: { en: 'Differential pressure gauges for filter and flow condition indication.', zh: '用于过滤和流量状态指示的差压表。' },
            sortOrder: 30,
            facetKeys: ['measurementRange', 'accuracyClass', 'processConnection'],
            seo: seo('/products/pressure-gauges/differential-pressure-gauges'),
          },
        ],
      },
      {
        id: 'cat_wireless_transmitters',
        parentId: rootCategoryId,
        depth: 1,
        kind: 'measurement-family',
        slug: 'wireless-transmitters',
        slugPath: 'wireless-transmitters',
        canonicalPath: '/products/wireless-transmitters',
        name: { en: 'Wireless Transmitters', zh: '无线传输变送器' },
        description: { en: 'Wireless pressure, temperature, and level transmitters.', zh: '无线压力、温度和液位变送器。' },
        sortOrder: 70,
        facetKeys: ['measurementRange', 'outputSignal', 'ingressProtection', 'certification'],
        seo: seo('/products/wireless-transmitters', 'Select {category} by measured variable, range, signal, and protection.'),
        children: [
          {
            id: 'cat_wireless_pressure_transmitters',
            parentId: 'cat_wireless_transmitters',
            depth: 2,
            kind: 'product-function',
            slug: 'wireless-pressure-transmitters',
            slugPath: 'wireless-transmitters/wireless-pressure-transmitters',
            canonicalPath: '/products/wireless-transmitters/wireless-pressure-transmitters',
            name: { en: 'Wireless Pressure Transmitters', zh: '无线压力变送器' },
            description: { en: 'Wireless pressure transmitters for remote monitoring.', zh: '用于远程监测的无线压力变送器。' },
            sortOrder: 10,
            facetKeys: ['measurementRange', 'outputSignal', 'ingressProtection'],
            seo: seo('/products/wireless-transmitters/wireless-pressure-transmitters'),
          },
          {
            id: 'cat_wireless_temperature_transmitters',
            parentId: 'cat_wireless_transmitters',
            depth: 2,
            kind: 'product-function',
            slug: 'wireless-temperature-transmitters',
            slugPath: 'wireless-transmitters/wireless-temperature-transmitters',
            canonicalPath: '/products/wireless-transmitters/wireless-temperature-transmitters',
            name: { en: 'Wireless Temperature Transmitters', zh: '无线温度变送器' },
            description: { en: 'Wireless temperature transmitters for remote temperature monitoring.', zh: '用于远程测温的无线温度变送器。' },
            sortOrder: 20,
            facetKeys: ['measurementRange', 'outputSignal', 'ingressProtection'],
            seo: seo('/products/wireless-transmitters/wireless-temperature-transmitters'),
          },
          {
            id: 'cat_wireless_level_transmitters',
            parentId: 'cat_wireless_transmitters',
            depth: 2,
            kind: 'product-function',
            slug: 'wireless-level-transmitters',
            slugPath: 'wireless-transmitters/wireless-level-transmitters',
            canonicalPath: '/products/wireless-transmitters/wireless-level-transmitters',
            name: { en: 'Wireless Level Transmitters', zh: '无线液位变送器' },
            description: { en: 'Wireless level transmitters for tanks, wells, and remote sites.', zh: '用于水箱、水井和远程现场的无线液位变送器。' },
            sortOrder: 30,
            facetKeys: ['measurementRange', 'outputSignal', 'ingressProtection'],
            seo: seo('/products/wireless-transmitters/wireless-level-transmitters'),
          },
        ],
      },
    ],
  },
} as const satisfies CategoryTree

export type CategoryPath = NonEmptyReadonlyArray<CategoryId>
