import type {
  ApplicationId,
  AssetId,
  CategoryId,
  DocumentId,
  EvidenceId,
  IndustryId,
  IngressProtectionCode,
  IsoDateString,
  LocaleCode,
  LocalizedText,
  NonEmptyReadonlyArray,
  ProductId,
  ProductVariantId,
  QuantityRange,
  QuantityValue,
  RevisionString,
  SeriesId,
  SlugSegment,
  SourceRef,
  UnitCode,
} from '@/lib/domain'
import type { SpecificationDefinition, SpecificationDefinitionRegistry } from '@/lib/domain'
import { defaultSpecificationRegistry, normalizeSpecificationRegistry, validateSpecificationDefinitionRegistry, validateSpecificationValueAgainstRegistry } from '@/lib/domain'
import type {
  CategoryNode,
  CategoryTree,
  CertificationCode,
  ElectricalConnectionKind,
  MeasurementKind,
  ProcessConnectionKind,
  ProductAsset,
  ProductAvailabilityStatus,
  ProductCommercialTerms,
  ProductConnectionSet,
  ProductCore,
  ProductDocument,
  ProductEnvironmentalLimits,
  ProductFamily,
  ProductLifecycleStatus,
  ProductMeasurement,
  ProductOptionValue,
  ProductSignalOutput,
  ProductSpecificationGroup,
  ProductSpecificationValue,
  ProductVariant,
  SensorProfile,
  SignalOutputKind,
  ValveProfile,
} from '@/lib/domain'

export const CMS_FACT_ADAPTER_VERSION = 'cms-fact-layer-domain-adapter-v1'

export const defaultCmsFactLocales = ['en', 'zh'] as const satisfies readonly LocaleCode[]

export const categorySystemGeneratedFields = [
  'canonical',
  'slug',
  'depth',
  'slugPath',
  'canonicalPath',
  'children',
  'breadcrumb',
  'seo',
  'seo.canonicalPath',
] as const

export const productSystemGeneratedFields = [
  'canonical',
  'slug',
  'identity',
  'classification',
  'categoryPath',
  'slugPath',
  'canonicalPath',
  'breadcrumb',
  'seo',
  'localizedSeo',
  'jsonld',
  'jsonLd',
  'jsonLD',
  'geoAi',
  'geo',
  'localizedGeoAi',
  'geoEntity',
  'entity',
] as const

export const cmsFactValidationRules = [
  'CMS stores facts only; domain projections are generated by the adapter layer.',
  'Category facts may provide only id, parentId, and name; slug is generated by the adapter.',
  'Category depth, slugPath, canonicalPath, children, breadcrumb, and SEO fields are system generated.',
  'Product identity, classification, SEO, JSON-LD, canonical paths, breadcrumbs, and GEO entity are system generated.',
  'Product facts must use public family values sensor or valve; legacy ser_* family values are normalized to family sensor and retained as seriesId.',
  'Sensor facts must include measurements with overload limits and outputs; valve facts must include valveProfile and are not required to provide sensor measurement/output/connection facts.',
  'Documents, assets, certifications, and commercial terms are optional CMS facts; GEO evidence is source-backed only when source documents are present.',
  'Category parent graph must have one root, no cycles, max depth 4, and unique sibling slugs.',
  'Product primary and additional categories must exist in the generated CategoryTree.',
  'Product ids, skus, and generated model slugs must be unique.',
] as const

export type FactLocaleMap<T> = Partial<Record<LocaleCode, T>>

export interface CategoryFact {
  readonly id: CategoryId
  readonly parentId: CategoryId | null
  readonly name: LocalizedText
}

export interface ProductFact {
  readonly id: ProductId
  readonly family: ProductFamily
  readonly core: ProductCore
  readonly sensorProfile?: SensorProfile
  readonly valveProfile?: ValveProfile
  readonly sku: string
  readonly model: string
  readonly seriesId?: SeriesId
  readonly brand: string
  readonly manufacturer?: string
  readonly availability: ProductAvailabilityStatus
  readonly releasedAt?: IsoDateString
  readonly revisedAt: IsoDateString

  readonly primaryCategoryId: CategoryId
  readonly additionalCategoryIds?: readonly CategoryId[]
  readonly industryIds: readonly IndustryId[]
  readonly applicationIds: readonly ApplicationId[]
  readonly measurementKinds: readonly MeasurementKind[]

  readonly name: LocalizedText
  readonly shortName: LocalizedText
  readonly summary: LocalizedText
  readonly highlights: readonly LocalizedText[]
  readonly applications: readonly LocalizedText[]

  readonly measurements?: readonly ProductMeasurement[]
  readonly outputs?: readonly ProductSignalOutput[]
  readonly connections?: ProductConnectionSet
  readonly environmentalLimits?: ProductEnvironmentalLimits
  readonly specificationGroups: readonly ProductSpecificationGroup[]
  readonly variants?: readonly ProductVariant[]
  readonly certifications?: readonly CertificationCode[]
  readonly documents?: readonly ProductDocument[]
  readonly assets?: readonly ProductAsset[]
  readonly commercialTerms?: ProductCommercialTerms
}

export interface CmsFactInput {
  readonly categoryFacts: readonly CategoryFact[]
  readonly productFacts: readonly ProductFact[]
}

export interface ProductFactValidationIssue {
  readonly index: number
  readonly id?: string
  readonly sku?: string
  readonly model?: string
  readonly path: string
  readonly message: string
}

export interface TolerantProductFact {
  readonly index: number
  readonly fact: ProductFact
}

export interface TolerantCmsFactInput {
  readonly categoryFacts: readonly CategoryFact[]
  readonly productFacts: readonly TolerantProductFact[]
  readonly rejectedProductFacts: readonly ProductFactValidationIssue[]
}

export interface CmsFactAdapterOptions {
  readonly locales?: readonly LocaleCode[]
  readonly defaultLocale?: LocaleCode
  readonly specificationRegistry?: SpecificationDefinitionRegistry | readonly SpecificationDefinition[]
  readonly validateSpecificationKeys?: boolean
}

export interface AdapterConfig {
  readonly locales: NonEmptyReadonlyArray<LocaleCode>
  readonly defaultLocale: LocaleCode
  readonly specificationRegistry: SpecificationDefinitionRegistry
  readonly validateSpecificationKeys: boolean
}

export interface CategoryFactGraph {
  readonly rootFact: CategoryFact
  readonly byId: ReadonlyMap<CategoryId, CategoryFact>
  readonly childrenByParentId: ReadonlyMap<CategoryId | null, readonly CategoryFact[]>
  readonly depthById: ReadonlyMap<CategoryId, number>
}

export class CmsFactValidationError extends Error {
  readonly path: string

  constructor(path: string, message: string) {
    super(`${path}: ${message}`)
    this.name = 'CmsFactValidationError'
    this.path = path
  }
}

export function normalizeAdapterConfig(options: CmsFactAdapterOptions = {}): AdapterConfig {
  const locales = toNonEmptyArray(options.locales?.length ? [...options.locales] : [...defaultCmsFactLocales], 'adapter.locales')
  const defaultLocale = options.defaultLocale ?? locales[0]

  if (!locales.includes(defaultLocale)) {
    reject('adapter.defaultLocale', `default locale '${defaultLocale}' is not present in locales`)
  }

  return {
    locales,
    defaultLocale,
    specificationRegistry: normalizeSpecificationRegistry(options.specificationRegistry ?? defaultSpecificationRegistry),
    validateSpecificationKeys: options.validateSpecificationKeys ?? true,
  }
}

export function normalizeCmsFactInput(value: unknown, options: CmsFactAdapterOptions = {}): CmsFactInput {
  const config = normalizeAdapterConfig(options)
  assertObject(value, 'cmsFacts')
  rejectUnknownFields(value, ['categoryFacts', 'productFacts'], 'cmsFacts')
  rejectIllegalFields(value, ['categoryTree', 'products', 'canonical', 'slug', 'categoryPath', 'seo', 'geoAi', 'geo', 'jsonld', 'jsonLd', 'jsonLD'], 'cmsFacts')

  assertArray(value.categoryFacts, 'cmsFacts.categoryFacts')
  assertArray(value.productFacts, 'cmsFacts.productFacts')

  const categoryFacts = value.categoryFacts.map((fact, index) => {
    assertCategoryFact(fact, `cmsFacts.categoryFacts[${index}]`, config.locales)
    return fact
  })
  const productFacts = value.productFacts.map((fact, index) => {
    const productFact = normalizeProductFact(fact, `cmsFacts.productFacts[${index}]`, config.locales)
    validateProductSpecificationKeys(productFact.specificationGroups, config.specificationRegistry, config.validateSpecificationKeys, `cmsFacts.productFacts[${index}].specificationGroups`)
    return productFact
  })

  return {
    categoryFacts,
    productFacts,
  }
}

export function normalizeCmsFactSourceInput(value: unknown, options: CmsFactAdapterOptions = {}): CmsFactInput {
  const config = normalizeAdapterConfig(options)
  assertObject(value, 'cmsFacts')
  rejectUnknownFields(value, ['categoryFacts', 'productFacts'], 'cmsFacts')
  rejectIllegalFields(value, ['categoryTree', 'products', 'canonical', 'slug', 'categoryPath', 'seo', 'geoAi', 'geo', 'jsonld', 'jsonLd', 'jsonLD'], 'cmsFacts')

  assertArray(value.categoryFacts, 'cmsFacts.categoryFacts')
  assertArray(value.productFacts, 'cmsFacts.productFacts')

  const categoryFacts = value.categoryFacts.map((fact, index) => {
    assertCategoryFact(fact, `cmsFacts.categoryFacts[${index}]`, config.locales)
    return fact
  })

  return {
    categoryFacts,
    productFacts: value.productFacts as readonly ProductFact[],
  }
}

export function normalizeCmsFactInputWithProductTolerance(value: unknown, options: CmsFactAdapterOptions = {}): TolerantCmsFactInput {
  const config = normalizeAdapterConfig(options)
  assertObject(value, 'cmsFacts')
  rejectUnknownFields(value, ['categoryFacts', 'productFacts'], 'cmsFacts')
  rejectIllegalFields(value, ['categoryTree', 'products', 'canonical', 'slug', 'categoryPath', 'seo', 'geoAi', 'geo', 'jsonld', 'jsonLd', 'jsonLD'], 'cmsFacts')

  assertArray(value.categoryFacts, 'cmsFacts.categoryFacts')
  assertArray(value.productFacts, 'cmsFacts.productFacts')

  const categoryFacts = value.categoryFacts.map((fact, index) => {
    assertCategoryFact(fact, `cmsFacts.categoryFacts[${index}]`, config.locales)
    return fact
  })
  const productFacts: TolerantProductFact[] = []
  const rejectedProductFacts: ProductFactValidationIssue[] = []

  value.productFacts.forEach((fact, index) => {
    try {
      const productFact = normalizeProductFact(fact, `cmsFacts.productFacts[${index}]`, config.locales)
      validateProductSpecificationKeys(productFact.specificationGroups, config.specificationRegistry, config.validateSpecificationKeys, `cmsFacts.productFacts[${index}].specificationGroups`)
      productFacts.push({ index, fact: productFact })
    } catch (error) {
      rejectedProductFacts.push(toProductFactValidationIssue(index, fact, error))
    }
  })

  return {
    categoryFacts,
    productFacts,
    rejectedProductFacts,
  }
}

export function assertCmsFactInput(value: unknown, options: CmsFactAdapterOptions = {}): asserts value is CmsFactInput {
  normalizeCmsFactInput(value, options)
}

export function isCmsFactInput(value: unknown, options: CmsFactAdapterOptions = {}): value is CmsFactInput {
  try {
    assertCmsFactInput(value, options)
    return true
  } catch {
    return false
  }
}

export function assertCategoryFact(
  value: unknown,
  path = 'categoryFact',
  locales: readonly LocaleCode[] = defaultCmsFactLocales,
): asserts value is CategoryFact {
  assertObject(value, path)
  rejectIllegalFields(value, categorySystemGeneratedFields, path)
  rejectUnknownFields(value, ['id', 'parentId', 'name'], path)

  assertStringWithPrefix(value.id, 'cat_', `${path}.id`)

  if (value.parentId !== null) {
    assertStringWithPrefix(value.parentId, 'cat_', `${path}.parentId`)
  }

  assertLocalizedText(value.name, `${path}.name`, locales)
}

export function isCategoryFact(value: unknown): value is CategoryFact {
  try {
    assertCategoryFact(value)
    return true
  } catch {
    return false
  }
}

export function assertProductFact(
  value: unknown,
  path = 'productFact',
  locales: readonly LocaleCode[] = defaultCmsFactLocales,
): asserts value is ProductFact {
  normalizeProductFact(value, path, locales)
}

export function normalizeProductFact(
  value: unknown,
  path = 'productFact',
  locales: readonly LocaleCode[] = defaultCmsFactLocales,
): ProductFact {
  assertObject(value, path)
  rejectIllegalFields(value, productSystemGeneratedFields, path)
  rejectUnknownFields(value, allowedProductFactFields, path)

  const core = normalizeProductCore(value, path, locales)
  const rawCore = readOptionalObject(value.core)
  const family = core.family
  const seriesId = readOptionalPrefixedString(value.seriesId, 'ser_', `${path}.seriesId`) ?? readLegacySeriesId(rawCore?.family ?? value.family, `${path}.family`)
  const availability = normalizeProductAvailability(value.availability, `${path}.availability`)

  assertStringWithPrefix(value.id, 'prd_', `${path}.id`)
  assertOptionalNonEmptyString(value.manufacturer, `${path}.manufacturer`)
  if (value.lifecycle !== undefined) {
    assertEnum(value.lifecycle, productLifecycleStatuses, `${path}.lifecycle`)
  }
  assertOptionalIsoDate(value.releasedAt, `${path}.releasedAt`)
  assertIsoDate(value.revisedAt, `${path}.revisedAt`)
  assertOptionalIdArray(value.additionalCategoryIds, 'cat_', `${path}.additionalCategoryIds`)
  assertIdArray(value.industryIds, 'ind_', `${path}.industryIds`, { allowEmpty: true })
  assertIdArray(value.applicationIds, 'app_', `${path}.applicationIds`, { allowEmpty: true })
  assertLocalizedTextArray(value.highlights ?? [], `${path}.highlights`, locales, { allowEmpty: true })
  assertLocalizedTextArray(value.applications ?? [], `${path}.applications`, locales, { allowEmpty: true })

  const sensorProfile = normalizeSensorProfile(value, path)
  const valveProfile = normalizeValveProfile(value, path)
  validateFamilyProfiles(family, sensorProfile, valveProfile, path)
  const measurements = sensorProfile?.measurements ?? []
  const outputs = sensorProfile?.outputs ?? []
  const measurementKinds = normalizeMeasurementKinds(value.measurementKinds, measurements, `${path}.measurementKinds`)
  const connections = sensorProfile?.connections ?? normalizeOptionalConnectionSet(value.connections, `${path}.connections`)
  const environmentalLimits = sensorProfile?.environmentalLimits ?? normalizeEnvironmentalLimits(value.environmentalLimits, valveProfile, `${path}.environmentalLimits`, {
    requireTemperature: Boolean(sensorProfile) || !valveProfile,
  })

  assertSpecificationGroups(value.specificationGroups, `${path}.specificationGroups`)
  if (value.variants !== undefined) {
    assertVariantArray(value.variants, `${path}.variants`)
  }
  if (value.certifications !== undefined) {
    assertEnumArray(value.certifications, certificationCodes, `${path}.certifications`, { allowEmpty: true })
  }
  if (value.documents !== undefined) {
    assertDocumentArray(value.documents, `${path}.documents`)
  }
  if (value.assets !== undefined) {
    assertAssetArray(value.assets, `${path}.assets`)
  }
  if (value.commercialTerms !== undefined) {
    assertCommercialTerms(value.commercialTerms, `${path}.commercialTerms`)
  }


  const highlights = value.highlights ?? []
  const applications = value.applications ?? []

  return {
    id: value.id as ProductId,
    family,
    core,
    sensorProfile,
    valveProfile,
    sku: core.sku,
    model: core.model,
    seriesId,
    brand: core.brand,
    manufacturer: value.manufacturer as string | undefined,
    availability,
    releasedAt: value.releasedAt as IsoDateString | undefined,
    revisedAt: value.revisedAt as IsoDateString,
    primaryCategoryId: core.primaryCategory,
    additionalCategoryIds: value.additionalCategoryIds as readonly CategoryId[] | undefined,
    industryIds: value.industryIds as readonly IndustryId[],
    applicationIds: value.applicationIds as readonly ApplicationId[],
    measurementKinds,
    name: core.name,
    shortName: core.shortName,
    summary: core.summary,
    highlights: highlights as readonly LocalizedText[],
    applications: applications as readonly LocalizedText[],
    measurements,
    outputs,
    connections,
    environmentalLimits,
    specificationGroups: value.specificationGroups as readonly ProductSpecificationGroup[],
    variants: value.variants as readonly ProductVariant[] | undefined,
    certifications: value.certifications as readonly CertificationCode[] | undefined,
    documents: value.documents as readonly ProductDocument[] | undefined,
    assets: value.assets as readonly ProductAsset[] | undefined,
    commercialTerms: value.commercialTerms as ProductCommercialTerms | undefined,
  }
}

export function isProductFact(value: unknown): value is ProductFact {
  try {
    assertProductFact(value)
    return true
  } catch {
    return false
  }
}

export function toProductFactValidationIssue(index: number, value: unknown, error: unknown): ProductFactValidationIssue {
  const raw = value && typeof value === 'object' && !Array.isArray(value) ? value as Record<string, unknown> : undefined
  const core = raw?.core && typeof raw.core === 'object' && !Array.isArray(raw.core) ? raw.core as Record<string, unknown> : undefined
  const cmsError = error instanceof CmsFactValidationError ? error : undefined

  return {
    index,
    id: readIssueString(raw?.id),
    sku: readIssueString(raw?.sku ?? core?.sku),
    model: readIssueString(raw?.model ?? core?.model),
    path: normalizeProductIssuePath(cmsError?.path, index),
    message: normalizeProductIssueMessage(error instanceof Error ? error.message : String(error), index),
  }
}

function normalizeProductIssuePath(path: string | undefined, index: number) {
  const fallback = `productFacts[${index}]`

  if (!path) {
    return fallback
  }

  return path
    .replace(/^cmsFacts\.productFacts\[\d+\]/, fallback)
    .replace(/^productFacts\[\d+\]/, fallback)
}

function normalizeProductIssueMessage(message: string, index: number) {
  return message
    .replace(/cmsFacts\.productFacts\[\d+\]/g, `productFacts[${index}]`)
    .replace(/productFacts\[\d+\]/g, `productFacts[${index}]`)
}

function readIssueString(value: unknown) {
  return typeof value === 'string' && value.trim() ? value : undefined
}

function normalizeProductCore(value: Record<string, unknown>, path: string, locales: readonly LocaleCode[]): ProductCore {
  const rawCore = value.core
  const core = readOptionalObject(rawCore)

  if (core) {
    rejectUnknownFields(core, ['family', 'sku', 'model', 'brand', 'primaryCategory', 'name', 'shortName', 'summary'], `${path}.core`)
  }

  const rawFamily = core?.family ?? value.family ?? value.seriesId ?? (value.valveProfile !== undefined ? 'valve' : 'sensor')
  const family = normalizeProductFamily(rawFamily, `${path}.core.family`)
  const primaryCategory = readRequiredPrefixedString(core?.primaryCategory ?? value.primaryCategory ?? value.primaryCategoryId, 'cat_', `${path}.core.primaryCategory`)

  assertNonEmptyString(core?.sku ?? value.sku, `${path}.core.sku`)
  assertNonEmptyString(core?.model ?? value.model, `${path}.core.model`)
  assertNonEmptyString(core?.brand ?? value.brand, `${path}.core.brand`)
  assertLocalizedText(core?.name ?? value.name, `${path}.core.name`, locales)
  assertLocalizedText(core?.shortName ?? value.shortName, `${path}.core.shortName`, locales)
  assertLocalizedText(core?.summary ?? value.summary, `${path}.core.summary`, locales)

  return {
    family,
    sku: (core?.sku ?? value.sku) as string,
    model: (core?.model ?? value.model) as string,
    brand: (core?.brand ?? value.brand) as string,
    primaryCategory,
    name: (core?.name ?? value.name) as LocalizedText,
    shortName: (core?.shortName ?? value.shortName) as LocalizedText,
    summary: (core?.summary ?? value.summary) as LocalizedText,
  }
}

function normalizeProductFamily(value: unknown, path: string): ProductFamily {
  assertNonEmptyString(value, path)

  if (value === 'sensor' || value.startsWith('ser_')) {
    return 'sensor'
  }

  if (value === 'valve') {
    return 'valve'
  }

  reject(path, 'expected product family sensor or valve')
}

function readLegacySeriesId(value: unknown, path: string): SeriesId | undefined {
  if (value === undefined) {
    return undefined
  }

  assertNonEmptyString(value, path)
  return value.startsWith('ser_') ? value as SeriesId : undefined
}

function validateFamilyProfiles(family: ProductFamily, sensorProfile: SensorProfile | undefined, valveProfile: ValveProfile | undefined, path: string) {
  if (family === 'sensor' && !sensorProfile) {
    reject(`${path}.sensorProfile`, 'sensor family requires sensorProfile or legacy measurements/outputs')
  }

  if (family === 'valve' && !valveProfile) {
    reject(`${path}.valveProfile`, 'valve family requires valveProfile')
  }
}

function normalizeSensorProfile(value: Record<string, unknown>, path: string): SensorProfile | undefined {
  const rawProfile = value.sensorProfile
  const profile = rawProfile && typeof rawProfile === 'object' && !Array.isArray(rawProfile) ? rawProfile as Record<string, unknown> : undefined

  if (profile) {
    rejectUnknownFields(profile, ['measurements', 'outputs', 'connections', 'environmentalLimits'], `${path}.sensorProfile`)
  }

  const measurements = profile?.measurements ?? value.measurements
  const outputs = profile?.outputs ?? value.outputs

  const hasLegacySensorProjection = value.measurements !== undefined || value.outputs !== undefined
  const hasEmptyLegacySensorProjection = !profile
    && Array.isArray(value.measurements)
    && value.measurements.length === 0
    && Array.isArray(value.outputs)
    && value.outputs.length === 0

  if ((!profile && !hasLegacySensorProjection) || hasEmptyLegacySensorProjection) {
    return undefined
  }

  assertProductMeasurementArray(measurements, `${path}.sensorProfile.measurements`, { requireOverloadLimit: true })
  assertProductOutputArray(outputs, `${path}.sensorProfile.outputs`)
  const connections = profile?.connections ?? value.connections
  const environmentalLimits = profile?.environmentalLimits ?? value.environmentalLimits

  if (connections !== undefined) {
    assertConnectionSet(connections, `${path}.sensorProfile.connections`)
  }
  if (environmentalLimits !== undefined) {
    assertEnvironmentalLimits(environmentalLimits, `${path}.sensorProfile.environmentalLimits`)
  }

  return {
    measurements: measurements as NonEmptyReadonlyArray<ProductMeasurement>,
    outputs: outputs as NonEmptyReadonlyArray<ProductSignalOutput>,
    connections: connections as ProductConnectionSet | undefined,
    environmentalLimits: environmentalLimits as ProductEnvironmentalLimits | undefined,
  }
}

function normalizeValveProfile(value: Record<string, unknown>, path: string): ValveProfile | undefined {
  const rawProfile = value.valveProfile
  if (rawProfile === undefined) {
    return undefined
  }

  assertObject(rawProfile, `${path}.valveProfile`)
  rejectUnknownFields(rawProfile, ['pressureRating', 'connection', 'material', 'mode', 'compatibleMedia', 'size'], `${path}.valveProfile`)
  assertNonEmptyString(rawProfile.pressureRating, `${path}.valveProfile.pressureRating`)
  assertNonEmptyString(rawProfile.connection, `${path}.valveProfile.connection`)
  assertNonEmptyString(rawProfile.material, `${path}.valveProfile.material`)
  assertNonEmptyString(rawProfile.mode, `${path}.valveProfile.mode`)
  assertStringArray(rawProfile.compatibleMedia, `${path}.valveProfile.compatibleMedia`, { allowEmpty: false })
  assertNonEmptyString(rawProfile.size, `${path}.valveProfile.size`)

  return {
    pressureRating: rawProfile.pressureRating,
    connection: rawProfile.connection,
    material: rawProfile.material,
    mode: rawProfile.mode,
    compatibleMedia: rawProfile.compatibleMedia as NonEmptyReadonlyArray<string>,
    size: rawProfile.size,
  }
}

function normalizeMeasurementKinds(value: unknown, measurements: readonly ProductMeasurement[], path: string): readonly MeasurementKind[] {
  if (value !== undefined) {
    assertEnumArray(value, measurementKinds, path, { allowEmpty: true })
    return value as readonly MeasurementKind[]
  }

  return [...new Set(measurements.map((measurement) => measurement.kind))]
}

function normalizeOptionalConnectionSet(value: unknown, path: string): ProductConnectionSet | undefined {
  if (value === undefined) {
    return undefined
  }

  assertConnectionSet(value, path)
  return value
}

function normalizeEnvironmentalLimits(
  value: unknown,
  valveProfile: ValveProfile | undefined,
  path: string,
  options: { readonly requireTemperature: boolean } = { requireTemperature: true },
): ProductEnvironmentalLimits {
  if (value !== undefined) {
    if (options.requireTemperature) {
      assertEnvironmentalLimits(value, path)
    } else {
      assertValveEnvironmentalLimits(value, path)
    }
    return value
  }

  return {
    wettedMaterials: valveProfile ? [valveProfile.material] : [],
    compatibleMedia: valveProfile?.compatibleMedia ?? [],
  }
}

function normalizeProductAvailability(value: unknown, path: string): ProductAvailabilityStatus {
  if (value === undefined) {
    return 'quote-required'
  }

  assertEnum(value, productAvailabilityStatuses, path)
  return value
}

function readRequiredString(value: unknown, path: string): string {
  assertNonEmptyString(value, path)
  return value
}

function readRequiredPrefixedString<TPrefix extends string>(value: unknown, prefix: TPrefix, path: string): `${TPrefix}${string}` {
  assertStringWithPrefix(value, prefix, path)
  return value
}

function readOptionalPrefixedString<TPrefix extends string>(value: unknown, prefix: TPrefix, path: string): `${TPrefix}${string}` | undefined {
  if (value === undefined) {
    return undefined
  }

  assertStringWithPrefix(value, prefix, path)
  return value
}

export function validateCategoryFacts(facts: readonly CategoryFact[], options: CmsFactAdapterOptions = {}): CategoryFactGraph {
  const config = normalizeAdapterConfig(options)

  if (facts.length === 0) {
    reject('categoryFacts', 'at least one category fact is required')
  }

  const byId = new Map<CategoryId, CategoryFact>()
  const childrenByParentId = new Map<CategoryId | null, CategoryFact[]>()

  facts.forEach((fact, index) => {
    const path = `categoryFacts[${index}]`
    assertCategoryFact(fact, path, config.locales)

    if (byId.has(fact.id)) {
      reject(`${path}.id`, `duplicate category id '${fact.id}'`)
    }

    byId.set(fact.id, fact)
    const children = childrenByParentId.get(fact.parentId) ?? []
    children.push(fact)
    childrenByParentId.set(fact.parentId, children)
  })

  const rootFacts = childrenByParentId.get(null) ?? []

  if (rootFacts.length !== 1) {
    reject('categoryFacts', `expected exactly one root category, found ${rootFacts.length}`)
  }

  for (const fact of facts) {
    if (fact.parentId && !byId.has(fact.parentId)) {
      reject(`categoryFacts.${fact.id}.parentId`, `unknown parent '${fact.parentId}'`)
    }
  }

  validateCategoryCycles(facts, byId)
  validateSiblingCategorySlugs(childrenByParentId, config.defaultLocale)

  const depthById = new Map<CategoryId, number>()

  function resolveDepth(fact: CategoryFact, stack: readonly CategoryId[] = []): number {
    const existingDepth = depthById.get(fact.id)

    if (existingDepth !== undefined) {
      return existingDepth
    }

    if (!fact.parentId) {
      depthById.set(fact.id, 0)
      return 0
    }

    if (stack.includes(fact.id)) {
      reject(`categoryFacts.${fact.id}.parentId`, 'category parent graph contains a cycle')
    }

    const parent = byId.get(fact.parentId)

    if (!parent) {
      reject(`categoryFacts.${fact.id}.parentId`, `unknown parent '${fact.parentId}'`)
    }

    const depth = resolveDepth(parent, [...stack, fact.id]) + 1

    if (depth > 4) {
      reject(`categoryFacts.${fact.id}.parentId`, `category depth ${depth} exceeds domain max depth 4`)
    }

    depthById.set(fact.id, depth)
    return depth
  }

  for (const fact of facts) {
    resolveDepth(fact)
  }

  return {
    rootFact: rootFacts[0],
    byId,
    childrenByParentId,
    depthById,
  }
}

export function validateProductFactsAgainstCategoryTree(
  facts: readonly ProductFact[],
  categoryTree: CategoryTree,
  options: CmsFactAdapterOptions = {},
) {
  const config = normalizeAdapterConfig(options)
  const categoryIds = new Set(flattenCategoryNodes(categoryTree.root).map((category) => category.id))

  facts.forEach((fact, index) => {
    const path = `productFacts[${index}]`
    assertProductFact(fact, path, config.locales)
    validateProductSpecificationKeys(fact.specificationGroups, config.specificationRegistry, config.validateSpecificationKeys, `${path}.specificationGroups`)

    if (!categoryIds.has(fact.primaryCategoryId)) {
      reject(`${path}.primaryCategoryId`, `unknown category '${fact.primaryCategoryId}'`)
    }

    const allCategoryIds = [fact.primaryCategoryId, ...(fact.additionalCategoryIds ?? [])]
    const uniqueCategoryIds = new Set(allCategoryIds)

    if (uniqueCategoryIds.size !== allCategoryIds.length) {
      reject(`${path}.additionalCategoryIds`, 'product category assignments contain duplicates')
    }

    for (const categoryId of fact.additionalCategoryIds ?? []) {
      if (!categoryIds.has(categoryId)) {
        reject(`${path}.additionalCategoryIds`, `unknown category '${categoryId}'`)
      }
    }

    const measuredKinds = new Set((fact.measurements ?? []).map((measurement) => measurement.kind))

    for (const measurementKind of fact.measurementKinds) {
      if (!measuredKinds.has(measurementKind)) {
        reject(`${path}.measurementKinds`, `measurement kind '${measurementKind}' has no matching measurement record`)
      }
    }
  })
}

export function validateProductIdentityConsistency(facts: readonly ProductFact[]) {
  const ids = new Set<ProductId>()
  const skus = new Set<string>()
  const modelSlugs = new Map<SlugSegment, ProductId>()

  facts.forEach((fact, index) => {
    const path = `productFacts[${index}]`
    assertProductFact(fact, path)

    if (ids.has(fact.id)) {
      reject(`${path}.id`, `duplicate product id '${fact.id}'`)
    }

    if (skus.has(fact.sku)) {
      reject(`${path}.sku`, `duplicate product sku '${fact.sku}'`)
    }

    const modelSlug = normalizeSlug(fact.model)

    if (!modelSlug) {
      reject(`${path}.model`, 'model did not produce a valid product slug')
    }

    const ownerProductId = modelSlugs.get(modelSlug)

    if (ownerProductId && ownerProductId !== fact.id) {
      reject(`${path}.model`, `generated model slug '${modelSlug}' conflicts with product '${ownerProductId}'`)
    }

    ids.add(fact.id)
    skus.add(fact.sku)
    modelSlugs.set(modelSlug, fact.id)
  })
}

export function reject(path: string, message: string): never {
  throw new CmsFactValidationError(path, message)
}

export function toNonEmptyArray<T>(values: readonly T[] | undefined, path: string): NonEmptyReadonlyArray<T> {
  if (!values?.length) {
    reject(path, 'expected a non-empty array')
  }

  return values as NonEmptyReadonlyArray<T>
}

export function normalizeSlug(value: string): SlugSegment | '' {
  const slug = value
    .trim()
    .toLowerCase()
    .replace(/&/g, ' and ')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')

  return slug as SlugSegment | ''
}

export function localizeFactText(text: LocalizedText, locale: LocaleCode) {
  return text[locale] || text.en || Object.values(text).find(Boolean) || ''
}

export function assertObject(value: unknown, path: string): asserts value is Record<string, unknown> {
  if (!value || typeof value !== 'object' || Array.isArray(value)) {
    reject(path, 'expected an object')
  }
}

function readOptionalObject(value: unknown): Record<string, unknown> | undefined {
  return value && typeof value === 'object' && !Array.isArray(value) ? value as Record<string, unknown> : undefined
}

export function assertArray(value: unknown, path: string): asserts value is readonly unknown[] {
  if (!Array.isArray(value)) {
    reject(path, 'expected an array')
  }
}

export function assertNonEmptyString(value: unknown, path: string): asserts value is string {
  if (typeof value !== 'string' || !value.trim()) {
    reject(path, 'expected a non-empty string')
  }
}

function assertOptionalNonEmptyString(value: unknown, path: string) {
  if (value !== undefined) {
    assertNonEmptyString(value, path)
  }
}

function assertStringWithPrefix<TPrefix extends string>(value: unknown, prefix: TPrefix, path: string): asserts value is `${TPrefix}${string}` {
  assertNonEmptyString(value, path)

  if (!value.startsWith(prefix)) {
    reject(path, `expected '${prefix}' prefix`)
  }
}

function assertIsoDate(value: unknown, path: string): asserts value is IsoDateString {
  assertNonEmptyString(value, path)

  if (!/^\d{4}-\d{2}-\d{2}$/.test(value)) {
    reject(path, 'expected ISO date in YYYY-MM-DD format')
  }
}

function assertOptionalIsoDate(value: unknown, path: string) {
  if (value !== undefined) {
    assertIsoDate(value, path)
  }
}

function assertSlugSegment(value: unknown, path: string): asserts value is SlugSegment {
  assertNonEmptyString(value, path)

  if (value !== normalizeSlug(value)) {
    reject(path, 'expected a lowercase URL slug segment')
  }
}

function assertLocalizedText(value: unknown, path: string, locales: readonly LocaleCode[]): asserts value is LocalizedText {
  assertObject(value, path)

  for (const locale of locales) {
    assertNonEmptyString(value[locale], `${path}.${locale}`)
  }

  for (const [locale, text] of Object.entries(value)) {
    if (text !== undefined && typeof text !== 'string') {
      reject(`${path}.${locale}`, 'expected localized text value to be a string')
    }
  }
}

function assertLocalizedTextArray(
  value: unknown,
  path: string,
  locales: readonly LocaleCode[],
  options: { readonly allowEmpty: boolean },
) {
  assertArray(value, path)

  if (!options.allowEmpty && value.length === 0) {
    reject(path, 'expected a non-empty array')
  }

  value.forEach((item, index) => assertLocalizedText(item, `${path}[${index}]`, locales))
}

function assertEnum<TValue extends string>(value: unknown, allowedValues: readonly TValue[], path: string): asserts value is TValue {
  assertNonEmptyString(value, path)

  if (!allowedValues.includes(value as TValue)) {
    reject(path, `expected one of: ${allowedValues.join(', ')}`)
  }
}

function assertEnumArray<TValue extends string>(
  value: unknown,
  allowedValues: readonly TValue[],
  path: string,
  options: { readonly allowEmpty: boolean },
) {
  assertArray(value, path)

  if (!options.allowEmpty && value.length === 0) {
    reject(path, 'expected a non-empty array')
  }

  value.forEach((item, index) => assertEnum(item, allowedValues, `${path}[${index}]`))
}

function assertIdArray<TPrefix extends string>(
  value: unknown,
  prefix: TPrefix,
  path: string,
  options: { readonly allowEmpty: boolean },
) {
  assertArray(value, path)

  if (!options.allowEmpty && value.length === 0) {
    reject(path, 'expected a non-empty array')
  }

  value.forEach((item, index) => assertStringWithPrefix(item, prefix, `${path}[${index}]`))
}

function assertOptionalIdArray<TPrefix extends string>(value: unknown, prefix: TPrefix, path: string) {
  if (value !== undefined) {
    assertIdArray(value, prefix, path, { allowEmpty: true })
  }
}

function assertNumber(value: unknown, path: string): asserts value is number {
  if (typeof value !== 'number' || Number.isNaN(value)) {
    reject(path, 'expected a number')
  }
}

function assertBoolean(value: unknown, path: string): asserts value is boolean {
  if (typeof value !== 'boolean') {
    reject(path, 'expected a boolean')
  }
}

function assertQuantityRange(value: unknown, path: string): asserts value is QuantityRange {
  assertObject(value, path)
  assertNumber(value.min, `${path}.min`)
  assertNumber(value.max, `${path}.max`)
  assertEnum(value.unit, unitCodes, `${path}.unit`)
  assertNonEmptyString(value.display, `${path}.display`)

  if (value.min > value.max) {
    reject(path, 'range min cannot be greater than max')
  }
}

function assertQuantityValue(value: unknown, path: string): asserts value is QuantityValue {
  assertObject(value, path)
  assertNumber(value.value, `${path}.value`)
  assertEnum(value.unit, unitCodes, `${path}.unit`)
  assertNonEmptyString(value.display, `${path}.display`)
}

function assertProductMeasurement(value: unknown, path: string, options: { readonly requireOverloadLimit: boolean }): asserts value is ProductMeasurement {
  assertObject(value, path)
  assertEnum(value.kind, measurementKinds, `${path}.kind`)
  assertQuantityRange(value.range, `${path}.range`)
  assertOptionalNonEmptyString(value.accuracy, `${path}.accuracy`)

  if (options.requireOverloadLimit && value.overloadLimit === undefined) {
    reject(`${path}.overloadLimit`, 'measurement overloadLimit is required at the adapter boundary')
  }

  if (value.overloadLimit !== undefined) {
    assertQuantityValue(value.overloadLimit, `${path}.overloadLimit`)
  }
}

function assertProductMeasurementArray(
  value: unknown,
  path: string,
  options: { readonly requireOverloadLimit: boolean },
) {
  assertArray(value, path)

  if (value.length === 0) {
    reject(path, 'expected at least one measurement')
  }

  value.forEach((item, index) => assertProductMeasurement(item, `${path}[${index}]`, options))
}

function assertProductOutput(value: unknown, path: string): asserts value is ProductSignalOutput {
  assertObject(value, path)
  assertEnum(value.kind, signalOutputKinds, `${path}.kind`)
  assertNonEmptyString(value.value, `${path}.value`)
  assertOptionalNonEmptyString(value.protocol, `${path}.protocol`)
  assertOptionalNonEmptyString(value.wiring, `${path}.wiring`)
}

function assertProductOutputArray(value: unknown, path: string) {
  assertArray(value, path)

  if (value.length === 0) {
    reject(path, 'expected at least one output')
  }

  value.forEach((item, index) => assertProductOutput(item, `${path}[${index}]`))
}

function assertConnectionSet(value: unknown, path: string): asserts value is ProductConnectionSet {
  assertObject(value, path)
  assertObject(value.process, `${path}.process`)
  assertEnum(value.process.kind, processConnectionKinds, `${path}.process.kind`)
  assertNonEmptyString(value.process.value, `${path}.process.value`)
  assertOptionalNonEmptyString(value.process.material, `${path}.process.material`)
  assertObject(value.electrical, `${path}.electrical`)
  assertEnum(value.electrical.kind, electricalConnectionKinds, `${path}.electrical.kind`)
  assertNonEmptyString(value.electrical.value, `${path}.electrical.value`)
}

function assertEnvironmentalLimits(value: unknown, path: string): asserts value is ProductEnvironmentalLimits {
  assertObject(value, path)

  if (value.ingressProtection !== undefined) {
    assertIngressProtection(value.ingressProtection, `${path}.ingressProtection`)
  }

  if (value.mediaTemperature !== undefined) {
    assertQuantityRange(value.mediaTemperature, `${path}.mediaTemperature`)
  }

  if (value.ambientTemperature !== undefined) {
    assertQuantityRange(value.ambientTemperature, `${path}.ambientTemperature`)
  }

  if (value.mediaTemperature === undefined && value.ambientTemperature === undefined) {
    reject(path, 'at least one temperature limit is required')
  }

  assertStringArray(value.wettedMaterials, `${path}.wettedMaterials`, { allowEmpty: false })
  assertStringArray(value.compatibleMedia, `${path}.compatibleMedia`, { allowEmpty: false })
}

function assertValveEnvironmentalLimits(value: unknown, path: string): asserts value is ProductEnvironmentalLimits {
  assertObject(value, path)

  if (value.ingressProtection !== undefined) {
    assertIngressProtection(value.ingressProtection, `${path}.ingressProtection`)
  }

  if (value.mediaTemperature !== undefined) {
    assertQuantityRange(value.mediaTemperature, `${path}.mediaTemperature`)
  }

  if (value.ambientTemperature !== undefined) {
    assertQuantityRange(value.ambientTemperature, `${path}.ambientTemperature`)
  }

  assertStringArray(value.wettedMaterials, `${path}.wettedMaterials`, { allowEmpty: false })
  assertStringArray(value.compatibleMedia, `${path}.compatibleMedia`, { allowEmpty: false })
}

function assertSpecificationGroups(value: unknown, path: string) {
  assertArray(value, path)

  if (value.length === 0) {
    reject(path, 'expected at least one specification group')
  }

  value.forEach((item, index) => assertSpecificationGroup(item, `${path}[${index}]`))
}

function assertSpecificationGroup(value: unknown, path: string): asserts value is ProductSpecificationGroup {
  assertObject(value, path)
  assertNonEmptyString(value.key, `${path}.key`)
  assertNonEmptyString(value.label, `${path}.label`)
  assertArray(value.values, `${path}.values`)

  if (value.values.length === 0) {
    reject(`${path}.values`, 'expected at least one specification value')
  }

  value.values.forEach((item, index) => assertSpecificationValue(item, `${path}.values[${index}]`))
}

function assertSpecificationValue(value: unknown, path: string): asserts value is ProductSpecificationValue {
  assertObject(value, path)
  assertNonEmptyString(value.key, `${path}.key`)
  assertNonEmptyString(value.label, `${path}.label`)

  if (!['string', 'number', 'boolean'].includes(typeof value.value)) {
    reject(`${path}.value`, 'expected string, number, or boolean')
  }

  if (value.unit !== undefined) {
    assertEnum(value.unit, unitCodes, `${path}.unit`)
  }

  assertNonEmptyString(value.display, `${path}.display`)

  if (value.sourceRefs !== undefined) {
    assertSourceRefArray(value.sourceRefs, `${path}.sourceRefs`, { allowEmpty: true })
  }
}

function validateProductSpecificationKeys(
  groups: readonly ProductSpecificationGroup[],
  registry: SpecificationDefinitionRegistry,
  enabled: boolean,
  path: string,
) {
  if (!enabled) {
    return
  }

  const registryErrors = validateSpecificationDefinitionRegistry(registry)

  for (const error of registryErrors) {
    reject('adapter.specificationRegistry', error)
  }

  groups.forEach((group, groupIndex) => {
    group.values.forEach((value, valueIndex) => {
      const valuePath = `${path}[${groupIndex}].values[${valueIndex}]`
      const errors = validateSpecificationValueAgainstRegistry(value, registry)

      for (const error of errors) {
        reject(valuePath, error)
      }
    })
  })
}

function assertVariantArray(value: unknown, path: string) {
  assertArray(value, path)
  value.forEach((item, index) => assertVariant(item, `${path}[${index}]`))
}

function assertVariant(value: unknown, path: string): asserts value is ProductVariant {
  assertObject(value, path)
  assertStringWithPrefix(value.id, 'var_', `${path}.id`)
  assertNonEmptyString(value.orderCode, `${path}.orderCode`)
  assertArray(value.optionValues, `${path}.optionValues`)
  value.optionValues.forEach((item, index) => assertOptionValue(item, `${path}.optionValues[${index}]`))

  if (value.measurements !== undefined) {
    assertProductMeasurementArray(value.measurements, `${path}.measurements`, { requireOverloadLimit: false })
  }

  if (value.outputs !== undefined) {
    assertProductOutputArray(value.outputs, `${path}.outputs`)
  }

  if (value.connections !== undefined) {
    assertConnectionSet(value.connections, `${path}.connections`)
  }

  assertEnum(value.availability, productAvailabilityStatuses, `${path}.availability`)
  if (value.lifecycle !== undefined) {
    assertEnum(value.lifecycle, productLifecycleStatuses, `${path}.lifecycle`)
  }
}

function assertOptionValue(value: unknown, path: string): asserts value is ProductOptionValue {
  assertObject(value, path)
  assertNonEmptyString(value.optionKey, `${path}.optionKey`)
  assertNonEmptyString(value.label, `${path}.label`)
  assertNonEmptyString(value.value, `${path}.value`)
  assertOptionalNonEmptyString(value.code, `${path}.code`)
}

function assertDocumentArray(value: unknown, path: string) {
  assertArray(value, path)

  value.forEach((item, index) => assertDocument(item, `${path}[${index}]`))
}

function assertDocument(value: unknown, path: string): asserts value is ProductDocument {
  assertObject(value, path)
  assertStringWithPrefix(value.id, 'doc_', `${path}.id`)
  assertNonEmptyString(value.title, `${path}.title`)
  assertEnum(value.kind, documentKinds, `${path}.kind`)
  assertNonEmptyString(value.href, `${path}.href`)
  assertOptionalNonEmptyString(value.contentLocale, `${path}.contentLocale`)
  assertOptionalNonEmptyString(value.revision, `${path}.revision`)
}

function assertAssetArray(value: unknown, path: string) {
  assertArray(value, path)
  value.forEach((item, index) => assertAsset(item, `${path}[${index}]`))
}

function assertAsset(value: unknown, path: string): asserts value is ProductAsset {
  assertObject(value, path)
  assertStringWithPrefix(value.id, 'asset_', `${path}.id`)
  assertEnum(value.kind, assetKinds, `${path}.kind`)
  assertNonEmptyString(value.href, `${path}.href`)
  assertNonEmptyString(value.alt, `${path}.alt`)
}

function assertCommercialTerms(value: unknown, path: string): asserts value is ProductCommercialTerms {
  assertObject(value, path)

  if (value.minimumOrderQuantity !== undefined) {
    assertNumber(value.minimumOrderQuantity, `${path}.minimumOrderQuantity`)
  }

  assertOptionalNonEmptyString(value.standardLeadTime, `${path}.standardLeadTime`)
  assertOptionalNonEmptyString(value.warranty, `${path}.warranty`)
  assertBoolean(value.oemCustomizable, `${path}.oemCustomizable`)
  assertBoolean(value.privateLabelAvailable, `${path}.privateLabelAvailable`)
}

function assertSourceRefArray(value: unknown, path: string, options: { readonly allowEmpty: boolean }) {
  assertArray(value, path)

  if (!options.allowEmpty && value.length === 0) {
    reject(path, 'expected a non-empty sourceRefs array')
  }

  value.forEach((item, index) => assertSourceRef(item, `${path}[${index}]`))
}

function assertSourceRef(value: unknown, path: string): asserts value is SourceRef {
  assertObject(value, path)

  if (typeof value.id !== 'string' || (!value.id.startsWith('doc_') && !value.id.startsWith('evidence_'))) {
    reject(`${path}.id`, 'expected doc_ or evidence_ source id')
  }

  assertNonEmptyString(value.label, `${path}.label`)
  assertOptionalNonEmptyString(value.href, `${path}.href`)

  if (value.page !== undefined) {
    assertNumber(value.page, `${path}.page`)
  }

  assertEnum(value.confidence, confidenceLevels, `${path}.confidence`)
}

function assertStringArray(value: unknown, path: string, options: { readonly allowEmpty: boolean }) {
  assertArray(value, path)

  if (!options.allowEmpty && value.length === 0) {
    reject(path, 'expected a non-empty array')
  }

  value.forEach((item, index) => assertNonEmptyString(item, `${path}[${index}]`))
}

function assertIngressProtection(value: unknown, path: string): asserts value is IngressProtectionCode {
  assertNonEmptyString(value, path)

  if (!/^IP\d\d$/.test(value)) {
    reject(path, 'expected IP ingress protection code')
  }
}

function validateCategoryCycles(facts: readonly CategoryFact[], byId: ReadonlyMap<CategoryId, CategoryFact>) {
  const visiting = new Set<CategoryId>()
  const visited = new Set<CategoryId>()

  function visit(fact: CategoryFact) {
    if (visited.has(fact.id)) {
      return
    }

    if (visiting.has(fact.id)) {
      reject(`categoryFacts.${fact.id}.parentId`, 'category parent graph contains a cycle')
    }

    visiting.add(fact.id)

    if (fact.parentId) {
      const parent = byId.get(fact.parentId)

      if (parent) {
        visit(parent)
      }
    }

    visiting.delete(fact.id)
    visited.add(fact.id)
  }

  facts.forEach(visit)
}

function validateSiblingCategorySlugs(childrenByParentId: ReadonlyMap<CategoryId | null, readonly CategoryFact[]>, locale: LocaleCode) {
  for (const [parentId, children] of childrenByParentId.entries()) {
    const slugs = new Set<SlugSegment>()

    for (const child of children) {
      const slug = normalizeSlug(localizeFactText(child.name, locale))

      if (!slug) {
        reject(`categoryFacts.${child.id}.name.${locale}`, 'category name did not produce a valid slug')
      }

      if (slugs.has(slug)) {
        reject(`categoryFacts.${parentId ?? 'root'}.children`, `duplicate generated sibling slug '${slug}'`)
      }

      slugs.add(slug)
    }
  }
}

function flattenCategoryNodes(root: CategoryNode): readonly CategoryNode[] {
  return [root, ...(root.children ?? []).flatMap((child) => flattenCategoryNodes(child))]
}

function rejectUnknownFields(value: Record<string, unknown>, allowedFields: readonly string[], path: string) {
  for (const key of Object.keys(value)) {
    if (!allowedFields.includes(key)) {
      reject(`${path}.${key}`, 'field is not allowed in CMS Fact input')
    }
  }
}

function rejectIllegalFields(value: unknown, illegalFields: readonly string[], path: string) {
  assertObject(value, path)

  for (const field of illegalFields) {
    if (hasNestedField(value, field.split('.'))) {
      reject(`${path}.${field}`, 'field is derived by the adapter and must not be provided by CMS')
    }
  }
}

function hasNestedField(value: unknown, pathParts: readonly string[]): boolean {
  if (!pathParts.length) {
    return true
  }

  if (!value || typeof value !== 'object') {
    return false
  }

  const [head, ...tail] = pathParts

  if (!Object.prototype.hasOwnProperty.call(value, head)) {
    return false
  }

  return tail.length === 0 || hasNestedField((value as Record<string, unknown>)[head], tail)
}

const allowedProductFactFields = [
  'id',
  'family',
  'core',
  'sensorProfile',
  'valveProfile',
  'sku',
  'model',
  'seriesId',
  'brand',
  'manufacturer',
  'lifecycle',
  'availability',
  'releasedAt',
  'revisedAt',
  'primaryCategory',
  'primaryCategoryId',
  'additionalCategoryIds',
  'industryIds',
  'applicationIds',
  'measurementKinds',
  'name',
  'shortName',
  'summary',
  'highlights',
  'applications',
  'measurements',
  'outputs',
  'connections',
  'environmentalLimits',
  'specificationGroups',
  'variants',
  'certifications',
  'documents',
  'assets',
  'commercialTerms',
] as const

const productLifecycleStatuses = [
  'draft',
  'active',
  'phase-out',
  'discontinued',
  'hidden',
] as const satisfies readonly ProductLifecycleStatus[]

const productAvailabilityStatuses = [
  'stock-model',
  'standard-lead-time',
  'configurable',
  'made-to-order',
  'quote-required',
  'not-available',
] as const satisfies readonly ProductAvailabilityStatus[]

const measurementKinds = [
  'pressure',
  'differential-pressure',
  'level',
  'temperature',
  'flow',
  'humidity',
  'conductivity',
  'ph',
  'position',
  'vibration',
  'speed',
  'switch-state',
] as const satisfies readonly MeasurementKind[]

const signalOutputKinds = [
  'analog-current',
  'analog-voltage',
  'relay',
  'switch',
  'pulse',
  'fieldbus',
  'wireless',
] as const satisfies readonly SignalOutputKind[]

const processConnectionKinds = [
  'thread',
  'flange',
  'clamp',
  'submersible-cable',
  'probe',
  'remote',
  'none',
] as const satisfies readonly ProcessConnectionKind[]

const electricalConnectionKinds = [
  'cable',
  'm12',
  'din43650',
  'terminal-head',
  'connector',
  'wireless',
  'custom',
] as const satisfies readonly ElectricalConnectionKind[]

const certificationCodes = [
  'ce',
  'rohs',
  'atex',
  'iecex',
  'sil',
  'iso9001',
  'food-grade',
  'marine',
  'custom',
] as const satisfies readonly CertificationCode[]

const unitCodes = [
  'pa',
  'kpa',
  'mpa',
  'bar',
  'mbar',
  'psi',
  'mh2o',
  'mm',
  'm',
  'c',
  'f',
  'k',
  'ma',
  'v',
  'mv',
  'hz',
  'percent',
  'ph',
  'us_cm',
  'cycle',
  'custom',
] as const satisfies readonly UnitCode[]

const documentKinds = [
  'datasheet',
  'manual',
  'certificate',
  'drawing',
  'catalog',
  'software',
] as const satisfies readonly ProductDocument['kind'][]

const assetKinds = [
  'primary-image',
  'gallery-image',
  'diagram',
  'dimension-drawing',
  'installation-photo',
] as const satisfies readonly ProductAsset['kind'][]

const confidenceLevels = [
  'source-backed',
  'derived',
  'editorial',
  'unverified',
] as const satisfies readonly SourceRef['confidence'][]

export type AdapterDocumentId = DocumentId
export type AdapterEvidenceId = EvidenceId
export type AdapterProductVariantId = ProductVariantId
export type AdapterRevisionString = RevisionString

