export {
  buildAnswerSummary,
  buildCategoryBreadcrumb,
  buildCategoryContext,
  buildCategoryOpenGraphMetadata,
  buildCategorySeoFields,
  buildCategoryTreeFromFacts,
  buildCategoryTreeWithBreadcrumbs,
  buildDomainFromCmsFacts,
  buildDomainFromCmsFactsWithProductTolerance,
  buildEvidence,
  buildFactTable,
  buildFAQPageSchema,
  buildGeoAiProfile,
  buildItemListSchema,
  buildLocalizedGeoAiProfiles,
  buildLocalizedProductSeoFields,
  buildProductJsonLd,
  buildProductOpenGraphMetadata,
  buildProductRecordFromFact,
  buildProductRecordsFromFacts,
  buildProductSeoFields,
  buildSelectionGuidance,
  categorySystemGeneratedFields,
  CMS_FACT_ADAPTER_VERSION,
  cmsFactValidationRules,
  defaultCmsFactLocales,
  flattenCategoryNodes,
  productSystemGeneratedFields,
  assertCategoryFact,
  assertCmsFactInput,
  assertProductFact,
  CmsFactValidationError,
  isCategoryFact,
  isCmsFactInput,
  isProductFact,
  normalizeCmsFactInput,
  normalizeCmsFactSourceInput,
  normalizeCmsFactInputWithProductTolerance,
} from '@/adapter/product.adapter'

export type {
  AIReadableIndustrialProduct,
  CategoryFact,
  CmsDomainBuildResult,
  CmsFactAdapterOptions,
  CmsFactInput,
  CmsTolerantDomainBuildResult,
  ProductFact,
  ProductFactValidationIssue,
} from '@/adapter/product.adapter'
